POST https://node-do-zero-58tv.onrender.com/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Esse é o primeiro vídeo",
  "duration": 100
}

###

GET https://node-do-zero-58tv.onrender.com/videos?search=video

###

PUT https://node-do-zero-58tv.onrender.com/videos/9c984734-bc2e-421b-b5de-889a0e9710fa
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o segundo vídeo",
  "duration": 120
}

###

DELETE https://node-do-zero-58tv.onrender.com/videos/9c984734-bc2e-421b-b5de-889a0e9710fa